### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by aurora2425** [z-mahmud22/Dlib_Windows_Python3.x#4]
When I try to install it appears this error:
ERROR: Wheel 'dlib' located at C:\3GTDM\IMAGEN\ProyectoFinal\dlib-19.22.99-cp39-cp39-win_amd64.whl is invalid.
How can I solve it?

**Comment by z-mahmud22** [comment]
Hi, I'm not sure what the issue is. Could you please check which version of python you are using? The particular file you mentioned needs to be installed with python 3.9. 

Please mention the complete error traceback, and your system information.

**Comment by aurora2425** [comment]
I'm using Python 3.9.18. When I execute the command appears this:
Processing c:\3gtdm\imagen\proyectofinal\dlib-19.22.99-cp39-cp39-win_amd64.whl
ERROR: Wheel 'dlib' located at C:\3GTDM\IMAGEN\ProyectoFinal\dlib-19.22.99-cp39-cp39-win_amd64.whl is invalid.

**Comment by z-mahmud22** [comment]
I'm not sure exactly what happened but I'm guessing the wheel file somehow got corrupted while downloading. Can you redownload the wheel file and verify the SHA-256 checksum? 

You can check the SHA-256 checksum by opening Windows PowerShell and executing the following command:
```
 Get-FileHash dlib-19.22.99-cp39-cp39-win_amd64.whl -Algorithm SHA256
```
and it should print exactly this:
```
Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          0FD828405C77AF2DF1FF6A09964A8BA7F14838C538D9017046804F353E9B4BC2       C:\Users\Administrator\Downlo...
```
The hash value from your file should match the hash value of the original file as mentioned here. If they are not the same then your downloaded wheel file is corrupted and you need to redownload a fresh copy. Check the file size as well, the original file size is about 2.82 MB.

**Comment by aurora2425** [comment]
I reinstalled anaconda and disabled the antivirus
